name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install hptt
        run: cd libs/hptt && make scalar && cd pythonAPI && uv run python setup.py install && export HPTT_ROOT=/home/runner/work/motip/motip/libs/hptt/pythonAPI/../

      - name: Install tccg
        run: cd libs/tccg && uv run python setup.py install && export TCCG_ROOT=/home/runner/work/motip/motip/libs/tccg

      - name: Run tests
        run: uv run pytest
